// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrT2_HDO9Y1g2UtkdVDlLwf22C88KWRs',
    appId: '1:213434716569:web:f1d4de70758e8e8643c308',
    messagingSenderId: '213434716569',
    projectId: 'instaclone-a4055',
    authDomain: 'instaclone-a4055.firebaseapp.com',
    storageBucket: 'instaclone-a4055.appspot.com',
    measurementId: 'G-G0D96C8TG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAED7Hb9cRZ_IHo3FeukV_L6kM8EPTnDmQ',
    appId: '1:213434716569:android:90610992bafec86243c308',
    messagingSenderId: '213434716569',
    projectId: 'instaclone-a4055',
    storageBucket: 'instaclone-a4055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0gxxhsIJuxQpYYEeDqa-TOqCrl_5p4mg',
    appId: '1:213434716569:ios:f05f1dfcabca4d9e43c308',
    messagingSenderId: '213434716569',
    projectId: 'instaclone-a4055',
    storageBucket: 'instaclone-a4055.appspot.com',
    iosBundleId: 'com.example.instaclone',
  );
}
